services:
  - type: web
    name: civil-unrest-forecaster-backend
    env: python
    runtime: python
    buildCommand: pip install -r requirements-deploy.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    plan: free
    branch: main
